### ISSUE TITLE
Remove Jaeger tracing exporter, document using OTLP exporter with Jaeger

### ISSUE THREAD

**Issue by divergentdave** [divviup/janus#1464]
Jaeger is recommending migrating to OTLP exporters instead of exporters for their own protocols. I tested this out with the `jaegertracing:all-in-one` image, and the opentelemetry-otlp exporter works fine with it. I used the following configuration:

```yaml
logging_config:
  open_telemetry_config:
    otlp:
      endpoint: http://localhost:4317/
```

(This uses the OTLP over gRPC server)
