### ISSUE TITLE
Improve Task serialization format

### ISSUE THREAD

**Issue by BranLwyd** [divviup/janus#329]
Tasks can be serialized; the most notable user of task serialization is probably the `janus_cli` `provision-tasks` command, which accepts a file with yaml-serialized task structures and writes them into the database.

But, the task structure leaves a lot to be desired. Here is an example `tasks.yaml` (note -- sensitive values are not redacted as this is a task I randomly generated for testing purposes):
```
---
- id: 6htUJt9aF2EShQy6CIoxBwq_Xqs_40l3kWMa9wQM3xQ
  aggregator_endpoints:
    - "http://leader_endpoint/"
    - "http://helper_endpoint/"
  vdaf: Prio3Aes128Count
  role: Leader
  vdaf_verify_keys:
    - 3b3szgpQuEsDs5YiekuTgg
  max_batch_lifetime: 0
  min_batch_size: 0
  min_batch_duration: 28800
  tolerable_clock_skew: 600
  collector_hpke_config:
    id: 112
    kem_id: X25519HkdfSha256
    kdf_id: HkdfSha256
    aead_id: Aes128Gcm
    public_key:
      - 4
      - 210
      - 112
      - 42
      - 107
      - 86
      - 101
      - 170
      - 130
      - 211
      - 209
      - 139
      - 116
      - 190
      - 85
      - 150
      - 136
      - 173
      - 152
      - 170
      - 216
      - 221
      - 118
      - 124
      - 110
      - 143
      - 229
      - 144
      - 81
      - 11
      - 140
      - 91
  agg_auth_tokens:
    - Y01mNVBRTVNMb1h0R0VpOGlMMHNZdw
    - cG9NLTJvZTlkZWh2WWJNNnJ4QS12QQ
  hpke_keys:
    - - id: 0
        kem_id: X25519HkdfSha256
        kdf_id: HkdfSha256
        aead_id: Aes128Gcm
        public_key:
          - 185
          - 225
          - 31
          - 216
          - 134
          - 84
          - 46
          - 95
          - 96
          - 7
          - 183
          - 21
          - 6
          - 55
          - 35
          - 134
          - 116
          - 172
          - 2
          - 226
          - 135
          - 80
          - 4
          - 119
          - 93
          - 240
          - 137
          - 204
          - 89
          - 192
          - 94
          - 78
      - cMYDfdJY9-SmIPkp2FbMY7HAayt1_xmHWdckrpMsSlM
    - - id: 1
        kem_id: X25519HkdfSha256
        kdf_id: HkdfSha256
        aead_id: Aes128Gcm
        public_key:
          - 92
          - 58
          - 7
          - 26
          - 104
          - 80
          - 211
          - 230
          - 24
          - 150
          - 14
          - 104
          - 14
          - 204
          - 58
          - 111
          - 207
          - 37
          - 208
          - 225
          - 192
          - 164
          - 88
          - 145
          - 4
          - 24
          - 2
          - 145
          - 52
          - 109
          - 148
          - 16
      - 0KOvGTJ7B0q9ihPebqC2XknYldUukCgBsV1Ls4YwM1Y
```

A few thoughts:
* We should encode HPKE public keys as we do HPKE private keys, i.e. in websafe base64 w/o padding, as opposed to encoding them as an array of bytes.
* `hpke_keys` is a list of (`HpkeConfig`, `HpkePrivateKey`) tuples. These tuples render as a two-element list. For serialization, we should take them to/from a serialization-only structure that gives these parts names.
